---
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { ruby: '2.7', allowed-failure: true }
          - { ruby: '3.0', allowed-failure: true }
          - { ruby: '3.1', allowed-failure: true }
          - { ruby: '3.2', allowed-failure: true }
          - { ruby: 'ruby-head', allowed-failure: true }
          - { ruby: 'truffleruby-head', allowed-failure: true }
          - { ruby: 'jruby-head', allowed-failure: true }
    name: test (${{ matrix.entry.ruby }})
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - run: bundle install --jobs=3 --retry=3 --path=vendor/bundle
      - run: bundle exec rake spec
        continue-on-error: ${{ matrix.entry.allowed-failure }}
